services:
  flutter_app:
    image: lmatrangolo/flutter-custom
    container_name: flutter_app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=8080
