apiVersion: v1
kind: Service
metadata:
  name: flutter-service
spec:
  type: NodePort
  selector:
    app: flutter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080