name: Flutter CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: write
  issues: write

jobs:
  flutter-ci:
    name: Flutter CI
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Run Flutter analyze and tests in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: lmatrangolo/flutter-custom
          options: --workdir /app
          run: |
            flutter pub get
            flutter analyze
            flutter test

  manual-approval:
    name: Manual Approval
    needs: flutter-ci
    runs-on: ubuntu-latest

    steps:
      - name: Wait for manual approval before deployment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: LucasGit10
          minimum-approvals: 1
          issue-title: 'Approval required to deploy to EC2'
          issue-body: 'The CI workflow has passed. Approve to deploy to the EC2 server.'

  build-web:
    name: Build Flutter Web
    needs: manual-approval
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build Flutter Web in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: lmatrangolo/flutter-custom
          options: --workdir /app -v ${{ github.workspace }}:/app
          run: |
            flutter pub get
            flutter build web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web

  deploy-to-ec2:
    name: Deploy to EC2
    needs: build-web
    runs-on: ubuntu-22.04

    steps:
      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-build
          path: ./build/web

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: '204.236.212.94'
          username: 'terraform-admin'

          key: |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCdaFBvbswj7s8jriOm3L8DAgFUxYXqfb+YmMey8NsH5OEyjo0mmXPv/B1kRr740xzvefQRNaGiri9JX9cRFyxXcPBRf7v0lGNzdR7j5Ym31L3iuDcyMt6wVcR1nYX6XfqG5+YacdFiXPUiv56FSryyd4Jqjj0bzJIBYL9IIWgNsBwRZ1yBwRi9qahSyHmBJEAi8atM2d1vMSrcuTRuiR/f6M2/n3L5Uhbc9wWK29GcFZzNzTXicdg0kz4NegU2d5ZoR8Mqh29yK4EHn02xW3zKdc0F6y4b5AMda2Gg1OjWt2hI+MYaUnU6+15cyqrwXApe6Kp3iArFrIC7Dl5PwBd/zp0xxBBkygjRuiB25u31hdY5AfH6S0ilDUQ3kRe12SGY5D0Z7PEaXU2n2drjMV4Nj39gh2ddY5Ipf5l/HsVr+Vke5udp/a2OA+6KOoh2+YqEVkYI+vNKqulbif/WZyKz/PY8K+asoh4PbhK45Ce2Tef0yyLqB6NHTFa0f5rkTDJmL+qVNNp1Bm/bgGDWmRzwRC27BV7qnX6YXdt6lfCRlYm+GKxbkK8X1QX/tE+U+CkJc8vyjk28AoiW8G8JLbPW/ja7XQrxomTTZZKvLXxDwNtvgQsCmApLxYnD/WHfGbVh8AtUMjihtGmrMnuiocgIUSBIaQ9EdW/dq0JiWaBCyQ== saori@saori-Dell-G15-5525

          script: |
            # Remove o conteúdo antigo do diretório do Nginx
            sudo rm -rf /var/www/html/*
            # Copia os novos arquivos da build para o diretório do Nginx
            sudo mv build/web/* /var/www/html/
            # Reinicia o Nginx para garantir que as alterações sejam aplicadas
            sudo systemctl restart nginx
