name: Flutter CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  flutter-ci:
    name: Flutter CI
    runs-on: ubuntu-22.04
    container:
      image: lmatrangolo/flutter-custom

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: |
          if [ -d "test" ]; then
            flutter test
          else
            echo "No test directory found. Skipping tests."
          fi

  manual-approval:
    name: Manual Approval
    needs: flutter-ci
    runs-on: ubuntu-22.04

    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: LucasGit10,itsuki-ALMA
          minimum-approvals: 2
          issue-title: 'Approval required to proceed with deployment'
          issue-body: 'The CI workflow passed. Do you approve proceeding to the next stage?'

  build-web:
    name: Build Web
    needs: manual-approval
    runs-on: ubuntu-22.04
    container:
      image: lmatrangolo/flutter-custom

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web
